dist: trusty
language: minimal
services:
  - docker

cache:
  directories:
    - vendor

git:
  depth: 1

env:
  matrix:
    - PHP_IMG="php-7.2-mongoext-1.3.0-20200327" MONGO_IMG="mongo:3.4"
    - PHP_IMG="php-7.3-mongoext-1.5.3-20200327" MONGO_IMG="mongo:4.0"
    - PHP_IMG="php-7.4-mongoext-1.6.0-20200327" MONGO_IMG="mongo:4.0"
    - PHP_IMG="php-7.4-mongoext-1.6.0-20200327" MONGO_IMG="mongo:4.0" SYMFONY="4.4.*"
    - PHP_IMG="php-7.4-mongoext-1.6.0-20200327" MONGO_IMG="mongo:4.0" SYMFONY="5.*"

before_install:
  - mv docker-compose.travis.yml docker-compose.override.yml
  - sudo chmod -R 777 . # ugly! Travis is 2000:2000
  - |
    if [ "$SYMFONY" != "" ]; then
      make lock-symfony-$SYMFONY
    fi;

install:
  - docker-compose run --no-deps --rm php composer install --prefer-dist --no-interaction ${COMPOSER_FLAGS}

before_script:
  - docker-compose run --no-deps --rm php composer validate

script:
  - docker-compose run --rm php bash -c "sleep 3; -v --coverage-clover=build/coverage-report.xml"
after_script:
  - bash <(curl -s https://codecov.io/bash) -f build/coverage-report.xml"

jobs:
  include:
    - stage: "Test"
      name: Lowest versions
      env: 
        PHP_IMG: 'php-7.2-mongoext-1.3.0-20200327'
        MONGO_IMG: 'mongo:3.4'
        SYMFONY: 3.4
      install:
        - docker-compose run --no-deps --rm php composer install --prefer-lowest --prefer-dist --no-interaction ${COMPOSER_FLAGS}
    - name: PHP 7.2
      env:
        PHP_IMG: 'php-7.2-mongoext-1.3.0-20200327'
    - name: PHP 7.3
      env:
        PHP_IMG: "php-7.3-mongoext-1.5.3-20200327"
    - env:
        SYMFONY: '3.4.*'
    - env:
        SYMFONY: '4.4.*'
    - env:
        SYMFONY: '5.0.*'
    - name: 'PHPStan'
      script:
        - docker-compose run --rm php vendor/bin/phpstan analyze
      after_script: false
    - name: 'Code Style'
      script:
        - docker-compose run --no-deps --rm php composer cs-check
      after_script: false
