version: "3.1"

services:
  php:
    image: local.example.com/php:${PHP_VERSION:-latest}
    build:
      context: docker/php
    volumes:
        - ./:/home/user-dev/project
    tty: true
    environment:
      XDEBUG_START_WITH_REQUEST: 'yes'
      XDEBUG_HOST: host.docker.internal
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    healthcheck:
      test: "bash /usr/local/bin/docker-healthcheck.sh"
      interval: 10s
      timeout: 5s
      retries: 10
    entrypoint: ["/usr/local/bin/facile-entrypoint.sh"]
    command: mongod
    volumes:
      - ./docker/mongo/mongo.keyfile:/mongo.keyfile
      - ./docker/mongo/facile-entrypoint.sh:/usr/local/bin/facile-entrypoint.sh
      - ./docker/mongo/docker-healthcheck.sh:/usr/local/bin/docker-healthcheck.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'rootPass'
