version: "3.1"

services:
  php:
    image: ilariopierbattista/mongodb-bundle-php:php-7.2-mongoext-1.3.0-20200327
    volumes:
        - ./:/home/user-dev/project
    tty: true
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
