version: "3.1"

services:
  php:
    image: local.example.com/php:${PHP_VERSION:-latest}
    build:
      context: docker/
    volumes:
        - ./:/home/user-dev/project
    tty: true
    
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    tmpfs:
      - /data/db:uid=1001
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'rootPass'
