<?php

declare(strict_types=1);

namespace Facile\MongoDbMessenger\Tests\End2End\App;

use Symfony\Component\ErrorHandler\Exception\FlattenException;
use Symfony\Component\Messenger\Stamp\RedeliveryStamp;

class SuppressDeprecationNormalizer extends ObjectNormalizerDecorator
{
    /**
     * @return array<string, bool>
     */
    public function getSupportedTypes(?string $format): array
    {
        return [
            FlattenException::class => true,
            RedeliveryStamp::class => true,
        ];
    }

    /**
     * @param mixed $data Data to restore
     * @param string $type
     * @param string|null $format
     * @param array<string, mixed>&array{ignored_attributes?: string[]} $context
     */
    public function denormalize($data, $type, $format = null, array $context = []): mixed
    {
        return parent::doDenormalize($data, $type, $format, $context); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $object
     * @param string|null $format
     * @param array<string, mixed>&array{ignored_attributes?: string[]} $context
     *
     * @return array<mixed>|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = []): \ArrayObject|array|string|int|float|bool|null
    {
        return $this->doNormalize($object, $format, $context);
    }
}
