<?php

declare(strict_types=1);

namespace Facile\MongoDbMessenger\Tests\End2End\App;

use Symfony\Component\Serializer\Normalizer\CacheableSupportsMethodInterface;

class SuppressDeprecationNormalizer extends ObjectNormalizerDecorator implements CacheableSupportsMethodInterface
{
    public function hasCacheableSupportsMethod(): bool
    {
        return $this->objectNormalizer->hasCacheableSupportsMethod();
    }

    /**
     * @param mixed $data Data to restore
     * @param string $type
     * @param string|null $format
     * @param array<string, mixed>&array{ignored_attributes?: string[]} $context
     */
    public function denormalize($data, $type, $format = null, array $context = [])
    {
        return parent::doDenormalize($data, $type, $format, $context); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $object
     * @param string|null $format
     * @param array<string, mixed>&array{ignored_attributes?: string[]} $context
     *
     * @return array<mixed>|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        return $this->doNormalize($object, $format, $context);
    }
}
