name: CI

on:
  pull_request: ~
  push:
    branches:
      - 1.x

jobs:
  tests:
    name: ${{ matrix.description }} - PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:${{ matrix.mongo }}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootPass
#        options: >-
#          --health-cmd '/etc/init.d/mongodb status || exit 1'
#          --health-interval 5s
#          --health-timeout 3s
#          --health-retries 5

    strategy:
      matrix:
        dependencies: ['highest']
        description: ['Tests']
        mongo: ['4.4']
        php:
          - 7.4
          - 7.3
          - 7.2
        script: ['bin/phpunit --coverage-clover=build/coverage-report.xml']
        include:
          - description: Symfony 4.4 LTS
            php: 7.4
            symfony: '4.4.*'
          - description: Prefer lowest
            dependencies: 'lowest'
            php: 7.2
            mongo: 3.4
            symfony: '4.4.*'
          - description: Infection
            php: 7.4
            mongo: '4.4'
            script: sleep 5; vendor/bin/infection --show-mutations

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mongodb-${{ matrix.ext-mongodb }}
      - name: Allow unstable dependencies
        run: composer config minimum-stability dev
        if: matrix.symfony == 'dev-master'
      - name: Restrict Symfony version
        run: composer require "symfony/symfony:${{ matrix.symfony }}" --no-update
        if: matrix.symfony
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: Await a bit for Mongo to spin up...
        run: sleep 10
      - name: Run tests
        run: ${{ matrix.script }}
      - name: Upload code coverage
        if: matrix.description != 'Infection'
        uses: codecov/codecov-action@v1
        with:
          file: build/coverage-report.xml
