name: CI

on:
  pull_request: ~
  push:
    branches:
      - 1.x
  schedule:
    - cron: "42 3 * * 1"

jobs:
  tests:
    name: ${{ matrix.description }} - PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies: ['highest']
        description: ['Tests']
        php: ['8.3']
        ext-mongodb: ['1.17.2']
        include:
          - php: '8.5'
            ext-mongodb: '2.1'
            composer_options: '--ignore-platform-req=php+'
          - description: Tests - driver v2
            php: '8.4'
            symfony-version: '7.*'
            ext-mongodb: '2.0'
          - description: Tests - Symfony 8
            php: '8.4'
            symfony-version: '8.*'
            ext-mongodb: '1.20.0' # 1.20 introduced PHP 8.4 support 
          - description: Tests - Symfony 7.4
            php: '8.3'
            symfony-version: '7.4.*'
            ext-mongodb: '1.15.3' # 1.15 introduced PHP 8.2 support 
          - description: Tests - Symfony 6.4
            php: '8.2'
            symfony-version: '6.4.*'
            ext-mongodb: '1.15.3' # 1.15 introduced PHP 8.2 support 
          - description: Tests - Symfony 5.4
            php: '8.1'
            ext-mongodb: '1.12.0' # 1.12 introduced PHP 8.1 support
            symfony-version: '5.4.*'
          - description: Prefer lowest
            dependencies: 'lowest'
            php: '8.1'
            symfony-version: '^5.4'
            ext-mongodb: '1.12.0'
            deprecations: disabled
          - description: Infection
            ext-mongodb: '1.12.0'
            php: '8.1'
            symfony-version: '5.4.*'

    env:
      MONGO_HOST: localhost
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare Docker Compose
        run: mv docker-compose.override.yml.dist docker-compose.override.yml
      - name: Starts MongoDB
        run: docker compose up -d mongo
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mongodb-${{ matrix.ext-mongodb }}
          coverage: xdebug
          tools: flex,composer:v2
      - name: Allow unstable dependencies
        run: composer config minimum-stability dev
        if: matrix.symfony-version == 'dev-master'
      - name: Remove Infection
        run: composer remove --dev --no-update infection/infection
        if: matrix.description != 'Infection'
      - name: Install dependencies
        uses: "ramsey/composer-install@v4"
        env:
          COMPOSER_NO_SECURITY_BLOCKING: "1"
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer_options }}
      - name: Await a bit for Mongo to spin up...
        run: timeout 60 nc -z localhost 27017
      - name: Run tests
        if: matrix.description != 'Infection'
        run: vendor/bin/phpunit --coverage-clover=build/coverage-report.xml
        env:
          SYMFONY_DEPRECATIONS_HELPER: ${{ matrix.deprecations }}
      - name: Run mutation testing
        if: matrix.description == 'Infection'
        run: vendor/bin/infection --show-mutations
      - name: Upload code coverage
        if: matrix.description != 'Infection'
        uses: codecov/codecov-action@v7
        with:
          files: build/coverage-report.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
