name: Static analysis

on:
  pull_request: ~
  push:
    branches:
      - 1.x
  schedule:
    - cron: "42 3 * * 1"

jobs:
  job:
    strategy:
      matrix:
        include:
          - description: Validate composer.json
            script: composer validate
          - description: Code style
            script: composer cs-check
          - description: PHPStan
            script: vendor/bin/phpstan analyze

    name: ${{ matrix.description }}
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: '6.4.*'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mongodb-1.17.2
      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
      - run: ${{ matrix.script }}
